### ISSUE TITLE
I love this!

### ISSUE THREAD

**Issue by lucymonie** [foundersandcoders/xhr-workshop#4]
I love this @skibinska! It's awesome and really cool.

I am slightly concerned that there's no way they can finish it in the time allowed. It took me half an hour and I've been mucking around with the giphy api quite a bit and understand apis. I'm wondering whether you would consider handing them everything except the actual API request. So all they have to do is write the request and figure out which part of the object to get so they can make an image appear.

I also wonder whether making it a single image might be easier for them to get their heads around rather than a list. 

Feel free to ignore if you prefer it how it is though. I know this is very last-minute feedback.

**Comment by skibinska** [comment]
Thanks @lucymonie :) But I think I will keep this version of workshop.

During the SCG on Friday I got the feedback that fizzbuzz was too easy and roman numerals too hard. And that wasn't anything in between. So I am hoping that this workshop will be something that push them a bit and prepare for @emilyb7 ' s one.  :)
