### ISSUE TITLE
Slightly unclear aim

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/xhr-workshop#5]
Hi, thanks for making this! We just did it today (FACN1)- one thing which I think could have been improved would be including an aim/a description of what we were aiming for at the top of the README- as it wasn't particularly clear what we were supposed to be doing without inferring from the files. 

Maybe you could change this before FAC10 does it tomorrow if you want? (I don't know whether this usually is the done thing, let me know if not!)

**Comment by skibinska** [comment]
Thanks for raising these issue @mattlub 

So if I understood it correctly in the README should be a description saying that _we will build an app that allows users to search for GIFs by a word or phrase and **gets a list of GIFs**_.

Is that right?

**Comment by mattlub** [comment]
yep I think that would be good.

**Comment by skibinska** [comment]
thanks:) done :+1:
